[package]
name = "mcm"
description = "Modern Clipboard Manager for Linux"
version = "0.1.0"
edition = "2021"

[dependencies]
wayland-client = "0.31.7"
wayland-protocols = "0.32.5"
wayland-protocols-wlr = { version = "0.3.6", features = ["client"] }
